pipeline {
   agent none
   stages {
      stage('Lint') {
         agent {
            docker { image 'alpine/cfn-lint'
                     args '--entrypoint='
            }
         }
         steps {
            catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
               sh "cfn-lint -f pretty templates/*"
            }
         }
      }
      stage('Nag') {
         agent {
            docker { image 'alpine/cfn-nag'
                     args '--entrypoint='
            }
         }
         steps {
            catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
               sh "cfn_nag_scan --input-path templates/*"
            }
         }
      }
   }
   // post {
   //    always {
   //       junit(
   //          allowEmptyResults: true,
   //          testResults: '*.xml'
   //       )
   //       recordIssues(
   //          enabledForFailure: true, aggregatingResults: true,
   //          tools: [java(), checkStyle(pattern: 'main.xml', reportEncoding: 'UTF-8')]
   //       )
   //    }
   // }
}
