pipeline {
   agent {
      docker { image 'python:3.7.2' }
   //    label 'slave'
   }
   
   stages {
      stage('Hello') {
          steps {
              // sh 'java -version'
              echo "Get working directory"
              sh 'pwd'
              sh 'python --version'
              sh 'pip --version'
              sh 'pip install -y cfn-lint'
          }
      }
   }
}
